sudo: required
services: 
  - docker

before_install: 
  - docker build -t ssetia85/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ssetia85/docker-react npm run test

language: generic
