sudo: required
services: 
  - docker

before_install: 
  - docker build -t ssetia85/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ssetia85/docker-react npm run test

language: generic

#deploy:
#   provider: elasticbeanstock
#   region: "us-east-1"
#   app: "docker-react"
#   environment: "Docker-env"
#   bucker_name: 
#   bucker_path: 
#   on:
#      branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
