sudo: required
services: 
  - docker

before_install: 
  - docker build -t ssetia85/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ssetia85/docker-react npm run test

language: generic

deploy:
   provider: elasticbeanstock
   region: "us-west-2"
   app: "Docker"
   environment: "Docker-env"
   bucker_name: "elasticbeanstalk-us-west-2-071819669202" 
   bucker_path: "docker"
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
